### ISSUE TITLE
Save workspace userfiles

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-projects#13]
There seem to be no extension that allow to { export / save with/near .code-workspace }/import Workspace operation saves ( `%userprofile%\AppData\Roaming\Code\User\workspaceStorage` . layout, etc. ) .
It can be useful and should protect these saves from overwrite by opening the same set of folders from other Workspace .

**Comment by L13** [comment]
This is handled by VS Code completely internal. As an extenstion developer, I have limited access to the user interface and working around the API can cause unexpected side effects. This seems to be something that has to be implemented by the VS Code team.
