### ISSUE TITLE
Ergonomics [workpaces list/-s]

### ISSUE THREAD

**Issue by irvnriir** [L13/vscode-projects#14]
* In the Workspaces list :
    * in RMB menu on newly opened Workspace, the logically being "Add Workspace To Project" button are named "Save As Project" .
    * no way to add a Workspace File trough the interface .
* Please add the Workspaces list to Explorer sidebar .

p.s. i see the extension as a layout/setup presets interface/manager (truly it seem to be no other use for it) .

**Comment by L13** [comment]
> * In the Workspaces list :
> 	* in RMB menu on newly opened Workspace, the logically being "Add Workspace To Project" button are named "Save As Project" .

A "Project" can be a folder or a .code-workspace file. It is the same like vscode folder and vscode workspace. Basically there a 3 simple types: Project (folder or workspace), Git Repository and VS Code (folder or workspace). So a "Project" means a **saved/picked** folder or workspace file. I can think about renaming the point for workspaces.


> * no way to add a Workspace File trough the interface .

If you have saved the workspace file, you can add it with "Projects: Add Project".

1. This is the first icon in the "Projects: Workspaces" view or press "Ctrl/Cmd + Shift + P" to open the command palette and search for "Projects: Add Project".
2. Now a dialog appears and you can select the workspace file or folder you want to add.

	
> * Please add the Workspaces list to Explorer sidebar .

This is still working. You can drag the "Projects: Workspaces" view to the file explorer icon, wait a second and if the sidebar shows up, let it drop where you want. This works with other views in the sidebar, too.

**Comment by irvnriir** [comment]
I just do not understand how Workspaces could need {any more attention / a new name} . I do not see any difference made by presence of git in the Workspace Folder .

"Projects: Add Project" doesn't allow to select files (only folders) .

"Projects: Workspaces" : thanks .

**Comment by L13** [comment]
> I just do not understand how Workspace Folders or Files could need {any more attention / a new name}, they seem to be handled by Workspaces all fine . I do not see any difference made by presence of git in the folder .

A project folder can be **every** folder. If two folders have the same name, you can change it in the list without changing the folder name. e.g. extensions. This folder exists in ~/.vscode and ~/.vscode-insiders.

The same for .code-workspace files. If they have the same name you can rename it without changing the original name.
e.g. multiple projects with same structure.
- project-a
	- .git
	- workspace-a.code-workspace
	- workspace-b.code-workspace
	- ...
- project-b
	- .git
	- workspace-a.code-workspace
	- workspace-b.code-workspace
	- ...

> "Projects: Add Project" doesn't allow to select files (only folders) .

Sorry, it seems to be my fault. I thought the dialog works on every os in the same way. But I see that this feature works only on macOS. I will fix it in the next release.

**Comment by irvnriir** [comment]
i see no case when the same names would make anything misbehave in default VSC .

**Comment by L13** [comment]
Maybe I have to explain it from a different point of view. The reason why I have written the extension was, that I wasn't really happy anymore with the extension "Project Manager" which I used before. At this time it wasn't possible to save workspaces and they made also another couple of changes. After that I made the decision to write my own one, which fits my needs. All the features you see are a result of what I have to challenge every day. And to get way better organized, I tried to find a mixture between how can I solve my problems and how can I write something that others can use, too. So if you don't need a feature that's fine. I recommend to ignore the projects part and instead you can use just the auto detection for .vscode folders, git repositories and .code-workspaces. It's the same with favorites or slots. Choose the best way for yourself how you want to work with.

**Comment by irvnriir** [comment]
I do not insist, just am interested in what is the use cases that i'm missing . ignore if its too long/bothering to describe/explain ,

**Comment by L13** [comment]
Hi, the new version has now a fix for adding workspaces. I added a new Icon and a new command on Windows and Linux. Not perfect, but it works. The wording can not be changed so easily, so I close the ticket. Maybe I put more focus on the extension next year. Right now is the goal to finish Diff Folders and go straight forward to version 1.0.0.
