### ISSUE TITLE
Non-project folders

### ISSUE THREAD

**Issue by Shatur** [L13/vscode-projects#15]
Hi! Thank you for the awesome extension.
I have a folder (`/mnt/Files/Code`) that contains only `CMakeLists.txt` files (CMake C++ folders). Is there a way to just display all folders from `/mnt/Files/Code`? I tried `l13Projects.vsCode.folders` and `l13Projects.workspace.folders` but it seems to work only for VSCode projects.
There is a similar feature in [vscode-project-manager](https://github.com/alefragnani/vscode-project-manager).

**Comment by L13** [comment]
Hi, the extension supports only auto detection for git repositories, workspace files and vscode folders. If you want to add other folders you have to use `Projects: Add Project`.

Which vscode-projects-manager feature do you mean?

**Comment by Shatur** [comment]
`vscode-projects-manager` allows you to specify folders in which all subfolders will be displayed as projects. In `vscode-projects-manager` such projects called `Any`.

> If you want to add other folders you have to use Projects: Add Project.

Yes, I know. But I suggest something like an option `l13Projects.Any.folders`. Like other already existing folder types (`l13Projects.vsCode.folders`, `l13Projects.workspace.folders`, etc), but just display all subdirectories.

Sorry if I was unclear.

**Comment by L13** [comment]
Thank you for the info. Right now where is no such feature like that and it was never planned. If I would implement something like that I have to rewrite a lot. I will think about it.

I don't want to force you to use vscode-project-manager, but if the other extension supports the feature you need, would you tell me why you are using my one? I had never the idea to compete with the other one. I just created it to solve my daily needs.

**Comment by Shatur** [comment]
> Right now where is no such feature like that and it was never planned. If I would implement something like that I have to rewrite a lot. I will think about it.

Okay, I will leave this issue open. I do not know TS, but maybe someone will be interested in this feature.

> I don't want to force you to use vscode-project-manager, but if the other extension supports the feature you need, would you tell me why you are using my one? I had never the idea to compete with the other one. I just created it to solve my daily needs.

I like you plugin much more :) Just one small feature I missing, not a problem.

**Comment by L13** [comment]
Hi, I have a question. I tested the feature in Project Manager and for me it ends up in a mess if I use projectManager.any.maxDepthRecursion with more than 1. Do you need this property or is it ok just to get the first level of subfolders?

**Comment by Shatur** [comment]
Hi, I agree, the first level of subfolders is enough for it.

**Comment by L13** [comment]
Hi, the new version has first level subfolder detection, which is now available.

**Comment by Shatur** [comment]
Thank you!
