### ISSUE TITLE
Feature Request: Add support for devcontainer environments

### ISSUE THREAD

**Issue by BerriJ** [L13/vscode-projects#16]
Hi there,

I love this extension. However, lately, I began using the vs-code remote container extension to develop inside a docker container. When I do, I open up my project folder and vs-code prompts me if I want to open this project inside the dev container.

Inside the devcontainer I can use this extension but when I add the project and exit the container, the does not open because the path isn't found.

However, opening up the project using the "recent files" works flawlessly. There you can see that I can open up the projects locally and directly inside the container (indicated by "[Dev Container]".

![Unbenannt](https://user-images.githubusercontent.com/37799358/91050144-8439a880-e61e-11ea-9ff2-131ee099ab9c.png)

Supporting those Dev Environments would definitely be awesome because they are gaining huge popularity recently.

Thanks in advance

**Comment by L13** [comment]
Hi, there are no plans for implementing remote features. Especially something like this needs time and right now I put my focus on the other extension "Diff Folders". The extension was never planned to go big. Just to solve my daily needs. I don't want to make promises which I can't hold. Maybe there is a chance but this will be next year. I recommend to use "Project Manager" which supports remote development. Sorry for the bad news.
