### ISSUE TITLE
Crash with latest vscode insiders

### ISSUE THREAD

**Issue by ptkdev** [L13/vscode-projects#22]
Stopped work with latest vscode insiders release 

`
[Extension Host] (node:42672) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:32:3))
`

`
events.js:292      throw er; // Unhandled 'error' event      ^Error: read ENOTCONN    at tryReadStart (net.js:573:20)    at Socket._read (net.js:584:5)    at Socket.Readable.read (_stream_readable.js:467:10)    at Socket.read (net.js:624:39)    at new Socket (net.js:376:12)    at Object.Socket (net.js:267:41)    at createSocket (internal/child_process.js:314:14)    at ChildProcess.spawn (internal/child_process.js:437:23)    at Object.spawn (child_process.js:557:9)    at /Users/ptkdev/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.160.0/dist/extension/extension.js:77:1099    at W (/Users/ptkdev/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.160.0/dist/extension/extension.js:76:499)Emitted 'error' event on Socket instance at:    at emitErrorNT (internal/streams/destroy.js:92:8)    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)    at processTicksAndRejections (internal/process/task_queues.js:84:21) {  errno: 'ENOTCONN',  code: 'ENOTCONN',  syscall: 'read'}
`

**Comment by L13** [comment]
Hi and thank you for the positive reviews.

The error confuses me, because the extension "ms-vscode-remote.remote-containers-0.160.0" is raising the message (see stack trace). I have tested the vscode insider version from today with only my extensions and everything works fine. It seems the remote extension is causing the issue.

**Comment by ptkdev** [comment]
I uninstalled `ms-vscode-remote.remote-containers-0.160.0` and works again! Thank's!
