### ISSUE TITLE
Please add subfolders

### ISSUE THREAD

**Issue by Escalion86** [L13/vscode-projects#34]
I have many projects, and they all lie in separate directories and subdirectories. Please add the ability to add subdirectories (group in group)

**Comment by L13** [comment]
Hi, the concept of this extension was never to rebuild the folder structure on the disk. If you need it I recommend to open the top folder for all directories and subdirectories in the VS Code explorer, then select the folder you want to open, right click to open the context menu and select `Open in Current Workspace` or `Open in New Workspace`. If you need this kind of workflow I also recommend to assign this top folder to a slot. So you can easily go to this folder back again.

If you want to add subdirectories automatically you can scan directories for folders with the property `l13Projects.subfolder.folders`. You can also scan for ´.git´ or ´.vscode´ projects.

If you want to sort detected projects you can to this by changing the property `l13Projects.sortWorkspacesBy` to `category` or `type`.

If you want to find a project with the quickmenu you can open all workspaces with `Cmd/Ctrl + Alt + Shift + P`. Now you can search for the project you want to open.

Another way to group workspaces is to assign tags. They can also be assigned to slots.

The concept of the extension is just to find and change projects much quicker and not to organize them like on disk.
