### ISSUE TITLE
Nested Group

### ISSUE THREAD

**Issue by hihahihahoho** [L13/vscode-projects#38]
Hi, is it possible to create a nest group?
For example:
Group:
|-Subgroup:
|--Project

**Comment by L13** [comment]
Hi and sorry, but this is not possible. This feature was still requested and you can find the answer here https://github.com/L13/vscode-projects/issues/34 A group is like a workspace for multiple windows instead as one file in one window how vscode is doing it. So you can open all folders in multiple windows at once. Making nested groups makes it too complex.

The next version I am working on will have the option to sort workspaces by root paths for scanned folders.
