### ISSUE TITLE
Unkown workspace

### ISSUE THREAD

**Issue by Small-Systems** [L13/vscode-projects#40]
Perhaps I'm not understanding something correctly about how to use this extension, but if I add a project to a group then I always have to same project/workspace appearing at the top of the list as "Unkown workspace", even if the folder has a .code-workspace file. Here's how it looks:

<img width="356" alt="Screenshot 2022-02-22 at 15 33 58" src="https://user-images.githubusercontent.com/2116283/155158421-2920649d-f964-4f96-b901-6959800c5838.png">

**Comment by L13** [comment]
Hi, I can reproduce the issue. The error appears if the setting "Sort Workspaces By" has the value "name" and the workspace is part of a group.

The extension is a spare time project so I have no time tables but I try to fix this in the next 2 or 3 weeks.

**Comment by L13** [comment]
The fix is out now and available on the VS Code marketplace.
