### ISSUE TITLE
Feature request: close workspace button

### ISSUE THREAD

**Issue by kimbar** [L13/vscode-projects#45]
That's it, that's the feature :)

A button or context menu item. I often need to return the VSC to the default text-editor mode, out of project-workspace-IDE-machinery. Your extension would be the perfect place for me.

BTW, thank you, It's really useful.

**Comment by L13** [comment]
Hi and thank you. This "button/context menu" still exists in the top menu. File > Close Workspace. A keyboard shortcut should be still assigned to, so you can close the workspace really quickly.
