### ISSUE TITLE
Way to bulk modify or access JSON for saved projects

### ISSUE THREAD

**Issue by kaleidawave** [L13/vscode-projects#46]
During some spring cleaning I renamed and moved my root folder, which now means all the projects I have saved now have incorrect paths:

![image](https://user-images.githubusercontent.com/26967284/231100150-867ddd9b-9f1c-4f66-af12-b744ce3b9536.png)

Is there a way to access the internal state in something like a JSON format so I can bulk modify these. Automatic file lookup doesn't quite work as I have too many folders, so prefer to do it manually. Thanks

**Comment by hacknug** [comment]
Select the Projects tab on your sidebar and click on the cog icon shown in the image. You'll get the json file you're looking for and be able to edit everything from there.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/1107521/231116481-a796aebb-8d42-4f47-9785-d777e8163e57.png">

**Comment by kaleidawave** [comment]
Hmm I don't seem to have the cog or refresh buttons? Only this dropdown

![image](https://user-images.githubusercontent.com/26967284/231129186-5101caf1-6490-42e9-9adb-798c55d42c6d.png)

**Comment by L13** [comment]
Hi, where is no official way to import/export the internal state, but the extension has commands for testing in dev mode. These commands allow to save/load the state as json. To activate this mode you have to checkout the repository, install all node modules, build the project and launch the dev mode in vscode. Now you have access to five commands for backup and restore. In the command palette they start all with "Developer:"

**Comment by L13** [comment]
> Select the Projects tab on your sidebar and click on the cog icon shown in the image. You'll get the json file you're looking for and be able to edit everything from there.

@hacknug I think you follow the wrong github repo. The extension you mentioned seems to be Projects+. https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus

**Comment by kaleidawave** [comment]
Awesome, managed to fix it
